export const introStyles = {
  overlay: "fixed inset-0 z-[120] bg-[#050505] text-white",
  frame: "relative grid h-full w-full grid-rows-[46vh_1fr] overflow-hidden md:grid-cols-[40%_60%] md:grid-rows-1",
  contentWrap: "relative z-20 flex items-start px-6 pb-28 pt-10 sm:px-10 sm:pb-32 sm:pt-12 lg:px-16 lg:pt-16",
  contentInner: "max-w-[27rem] space-y-5 md:space-y-6",
  logo: "text-sm tracking-[0.34em] uppercase text-white/88",
  headline: "text-balance text-4xl leading-[1.04] sm:text-5xl lg:text-[3.75rem]",
  description: "max-w-[30ch] text-sm leading-relaxed text-white/72 sm:text-base",
  bottomIndicator: "absolute inset-x-0 bottom-8 z-30 flex flex-col items-center gap-1 text-center text-white/40",
  imagePane: "relative order-first h-[46vh] min-h-[18rem] md:order-none md:h-full",
  imageSurface: "relative h-full w-full overflow-hidden md:rounded-l-[2rem]",
  imageFrame: "relative h-full w-full scale-[0.9] md:scale-[0.88]",
  image: "object-cover object-[50%_0%] md:object-[68%_center] lg:object-[72%_center]",
  cinematicShade: "pointer-events-none absolute inset-0 bg-black/28",
  leftGradient: "pointer-events-none absolute inset-0 bg-gradient-to-r from-[#050505] via-black/38 to-transparent",
  vignette: "pointer-events-none absolute inset-0 shadow-[inset_0_0_220px_rgba(0,0,0,0.3)]",
  lightSweep: "pointer-events-none absolute inset-y-0 -left-1/3 w-1/2 bg-gradient-to-r from-transparent via-white/[0.045] to-transparent",
} as const;
