import type { DesignTokens } from "@/types/design-tokens";

export const DESIGN_TOKENS: DesignTokens = {
  colors: {
    primary: "var(--color-primary)",
    secondary: "var(--color-secondary)",
    accent: "var(--color-accent)",
    background: "var(--color-background)",
    surface: "var(--color-surface)",
    border: "var(--color-border)",
    text: "var(--color-text)",
    muted: "var(--color-muted)",
  },
  typography: {
    display: "var(--font-size-display)",
    h1: "var(--font-size-h1)",
    h2: "var(--font-size-h2)",
    h3: "var(--font-size-h3)",
    h4: "var(--font-size-h4)",
    h5: "var(--font-size-h5)",
    h6: "var(--font-size-h6)",
    body: "var(--font-size-body)",
    small: "var(--font-size-small)",
    caption: "var(--font-size-caption)",
  },
  spacing: {
    xs: "var(--space-1)",
    sm: "var(--space-2)",
    md: "var(--space-4)",
    lg: "var(--space-6)",
    xl: "var(--space-8)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    full: "var(--radius-full)",
  },
  shadow: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
  },
  motion: {
    fast: "var(--duration-fast)",
    base: "var(--duration-base)",
    slow: "var(--duration-slow)",
    easingStandard: "var(--easing-standard)",
    easingEmphasized: "var(--easing-emphasized)",
  },
  breakpoints: {
    xs: "var(--breakpoint-xs)",
    sm: "var(--breakpoint-sm)",
    md: "var(--breakpoint-md)",
    lg: "var(--breakpoint-lg)",
    xl: "var(--breakpoint-xl)",
    xxl: "var(--breakpoint-2xl)",
  },
  containers: {
    xs: "var(--container-xs)",
    sm: "var(--container-sm)",
    md: "var(--container-md)",
    lg: "var(--container-lg)",
    xl: "var(--container-xl)",
    xxl: "var(--container-2xl)",
  },
  buttons: {
    primaryBg: "var(--button-primary-bg)",
    primaryFg: "var(--button-primary-fg)",
    secondaryBg: "var(--button-secondary-bg)",
    secondaryFg: "var(--button-secondary-fg)",
    accentBg: "var(--button-accent-bg)",
    accentFg: "var(--button-accent-fg)",
  },
  cards: {
    defaultBg: "var(--card-default-bg)",
    defaultBorder: "var(--card-default-border)",
    outlineBg: "var(--card-outline-bg)",
    outlineBorder: "var(--card-outline-border)",
    premiumBg: "var(--card-premium-bg)",
    premiumBorder: "var(--card-premium-border)",
  },
};
